### PR TITLE
Use windows-bindgen to generate only necessary bindings

### PR DESCRIPTION
**Pull request by djc**
Not sure if you're aware of this, but after reading your blog post (and especially since you mentioned "I'd rather have less code in my executables in general"), this might be interesting? Just showing that this can work.

### CODE REVIEW

**Comment by evmar** [comment]
Oh interesting!  Is it the same code generator used by windows-sys?  What is the benefit, I guess less code in the crate? 

...but it's only declarations so it's only a compile-time thing, right?  And then this is maybe more code at compile time because it's doing the bindings generation as part of its computation?  

It's funny, there's a whole FAQ-like section about windows vs windows-sys, I need one about this crate too :)
https://kennykerr.ca/rust-getting-started/windows-or-windows-sys.html

**Comment by evmar** [comment]
This makes me wonder if I should be deriving some of my *implementations* of the Windows API from this binding generator, hrmm

https://github.com/evmar/retrowin32/blob/c498c8a0a5977cbf558a6ed33239cd77a247a552/win32/src/winapi/ddraw/ddraw1.rs#L22

**Comment by djc** [comment]
Yes, it should be the same code and the benefit is indeed that there's less code that gets included at compile time (assuming dead code elimination works well it might not make a difference after compilation?). With Cargo features you still have to download all of windows-sys and then a bunch of stuff gets disabled during compilation.

**Comment by evmar** [comment]
Sorry for not responding, I wasn't sure what to do with this.  I think it's got pros and cons and I couldn't conclude what the balance was.  I think retrowin32 now uses windows-sys in a few different places with different subsets of API so the thing where Rust unifies the features so things just work is a big benefit.  I think windows-bindgen ends up being about as large too (just in XML) because it includes the whole windows API for generation purposes.

**Pull request closed without merging**
