### PR TITLE
add CreatePalette stub

### PR DESCRIPTION
**Pull request by LinusU**
stub version of #49, will rebase that one on this after merge

### CODE REVIEW

**Comment by evmar** [comment]
Aw bummer, I can see that the gdi32.dll conflict is gonna be a repeated annoyance.  What to do, hrmm....

**Comment by evmar** [comment]
(change looks good otherwise)

**Comment by evmar** [comment]
rebased/merged manually

**Comment by LinusU** [comment]
Yeah, it's a bit annoying 😅 

I've been submitting just one PR per dll file earlier, but missed it here. Thanks for merging manually 🙏

**Pull request closed without merging**
